GET http://localhost:3333/api/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjM4OGYwMjAyLTQ0Y2ItNGYyYy05NzZlLTgwMzFkNDQwZmJkYyIsIm5hbWUiOiJWaW5pY2l1cyBQIiwiZW1haWwiOiJ2aW5pY2l1c3BvYTJAZ21haWwuY29tIiwiaWF0IjoxNjUxMTYzMzYwLCJleHAiOjE2NTExNzA1NjB9.KTeKuJadt4E81hvwX3gAoCF1z6DGJWRSe9hh1xi-8BE
